// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqh8x9p-jn0fF93F_7GXbEhX4RvRHMQ08',
    appId: '1:383134210909:web:39f181794397a01107e6b4',
    messagingSenderId: '383134210909',
    projectId: 'elderly-companion-app',
    authDomain: 'elderly-companion-app.firebaseapp.com',
    storageBucket: 'elderly-companion-app.firebasestorage.app',
    measurementId: 'G-15ZF8TG3K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNuN9H63AymB7DqIVXlJW1COtEKwIhAI',
    appId: '1:383134210909:android:eb764eddc115ff9c07e6b4',
    messagingSenderId: '383134210909',
    projectId: 'elderly-companion-app',
    storageBucket: 'elderly-companion-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6R1K5QAQd1cvFF5dZAQpJCWSXmv0Efrg',
    appId: '1:383134210909:ios:9fa0b24197e7788e07e6b4',
    messagingSenderId: '383134210909',
    projectId: 'elderly-companion-app',
    storageBucket: 'elderly-companion-app.firebasestorage.app',
    iosClientId: '383134210909-5jq1s61coeadsjaokcl0jkm91lt38jo2.apps.googleusercontent.com',
    iosBundleId: 'com.snehitudu.app',
  );

}